import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PatientLayout from "./components/PatientLayout";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3001";

const getAuthHeaders = () => ({
  Authorization: `Bearer ${localStorage.getItem("token")}`,
  "Content-Type": "application/json",
});

const STATUS_STYLE = {
  normal: {
    label: "Normal",
    badge: "bg-emerald-100 text-emerald-700 border border-emerald-200",
    dot: "bg-emerald-500",
    icon: "check_circle",
    iconColor: "text-emerald-500",
  },
  borderline: {
    label: "Borderline",
    badge: "bg-amber-100 text-amber-700 border border-amber-200",
    dot: "bg-amber-500",
    icon: "warning",
    iconColor: "text-amber-500",
  },
  high: {
    label: "High",
    badge: "bg-red-100 text-red-700 border border-red-200",
    dot: "bg-red-500",
    icon: "arrow_upward",
    iconColor: "text-red-500",
  },
  low: {
    label: "Low",
    badge: "bg-blue-100 text-blue-700 border border-blue-200",
    dot: "bg-blue-500",
    icon: "arrow_downward",
    iconColor: "text-blue-500",
  },
};

const defaultStatus = {
  label: "Reviewed",
  badge: "bg-gray-100 text-gray-600 border border-gray-200",
  dot: "bg-gray-400",
  icon: "info",
  iconColor: "text-gray-400",
};

export default function PatientNutrition() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [hasData, setHasData] = useState(false);
  const [recommendations, setRecommendations] = useState(null);
  const [labOrders, setLabOrders] = useState([]);

  useEffect(() => {
    const fetchRecommendations = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`${API_BASE_URL}/api/nutrition/recommendations`, {
          headers: getAuthHeaders(),
        });
        if (!res.ok) throw new Error("Failed to fetch recommendations");
        const data = await res.json();
        setHasData(data.hasData);
        setRecommendations(data.recommendations);
        setLabOrders(data.labOrders || []);
      } catch (err) {
        setError(err.message || "Something went wrong");
      } finally {
        setLoading(false);
      }
    };
    fetchRecommendations();
  }, []);

  return (
    <PatientLayout title="Nutrition">
      <div className="space-y-6">
        {/* Header banner */}
        <div
          className="relative overflow-hidden rounded-3xl p-6 md:p-8 text-white"
          style={{
            background: "linear-gradient(135deg,#16a34a 0%,#22c55e 55%,#4ade80 100%)",
          }}
        >
          <div className="absolute top-0 right-0 w-64 h-64 rounded-full -mr-20 -mt-20 bg-white/5" />
          <div className="absolute bottom-0 left-16 w-40 h-40 rounded-full -mb-16 bg-white/5" />
          <div className="relative flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-3">
                <span
                  className="material-symbols-outlined text-white/80 text-lg"
                  style={{ fontVariationSettings: "'FILL' 1" }}
                >
                  nutrition
                </span>
                <span className="text-white/70 text-xs font-semibold uppercase tracking-widest">
                  AI-Powered · Based on your lab results
                </span>
              </div>
              <h2 className="text-2xl md:text-3xl font-black">
                Nutrition Insights
              </h2>
              <p className="text-white/70 mt-1.5 text-sm max-w-lg">
                Personalized dietary recommendations generated by AI from your
                completed lab results.
              </p>
            </div>
            <button
              onClick={() =>
                navigate("/patient/doctors", {
                  state: { specialtyFilter: "Nutritionist" },
                })
              }
              className="flex items-center gap-2 px-5 py-3 bg-white/15 hover:bg-white/25 text-white rounded-xl text-sm font-bold border border-white/20 hover:scale-105 transition-all self-start md:self-auto backdrop-blur-sm shrink-0"
            >
              <span className="material-symbols-outlined text-sm">
                person_search
              </span>
              Find Nutritionist
            </button>
          </div>
        </div>

        {/* Content */}
        {loading ? (
          <div className="bg-white rounded-2xl border border-gray-100 p-16 flex flex-col items-center justify-center gap-4">
            <div className="w-12 h-12 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin" />
            <div className="text-center">
              <p className="font-bold text-gray-700">Analysing your lab results…</p>
              <p className="text-sm text-gray-400 mt-1">
                Our AI is preparing personalised nutrition recommendations
              </p>
            </div>
          </div>
        ) : error ? (
          <div className="bg-white rounded-2xl border border-red-100 p-12 text-center">
            <span className="material-symbols-outlined text-4xl text-red-300 mb-3 block">
              error
            </span>
            <p className="font-bold text-gray-700 mb-1">Something went wrong</p>
            <p className="text-sm text-gray-400 mb-5">{error}</p>
            <button
              onClick={() => window.location.reload()}
              className="px-5 py-2.5 bg-emerald-500 text-white text-sm font-bold rounded-xl hover:bg-emerald-600 transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : !hasData ? (
          /* No lab results yet */
          <div className="bg-white rounded-2xl border border-gray-100 p-14 text-center">
            <div className="w-16 h-16 rounded-2xl bg-emerald-50 flex items-center justify-center mx-auto mb-4">
              <span className="material-symbols-outlined text-3xl text-emerald-400">
                biotech
              </span>
            </div>
            <h3 className="font-bold text-gray-800 text-lg mb-2">
              No lab results available yet
            </h3>
            <p className="text-gray-400 text-sm max-w-sm mx-auto mb-6 leading-relaxed">
              Nutrition recommendations are generated from your completed lab
              tests. Ask your doctor to order relevant lab tests and once
              results are ready they will appear here automatically.
            </p>
            <button
              onClick={() =>
                navigate("/patient/doctors", {
                  state: { specialtyFilter: "Nutritionist" },
                })
              }
              className="inline-flex items-center gap-2 px-5 py-2.5 text-white text-sm font-bold rounded-xl hover:scale-105 transition-all"
              style={{ background: "linear-gradient(135deg,#16a34a,#22c55e)" }}
            >
              <span className="material-symbols-outlined text-sm">
                person_search
              </span>
              Find a Nutritionist
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            {/* AI Summary */}
            {recommendations?.summary && (
              <div className="bg-white rounded-2xl border border-emerald-100 p-6">
                <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2">
                  <span className="material-symbols-outlined text-emerald-500">
                    smart_toy
                  </span>
                  AI Nutritional Assessment
                </h3>
                <p className="text-sm text-gray-600 leading-relaxed">
                  {recommendations.summary}
                </p>
              </div>
            )}

            {/* Lab Markers */}
            {recommendations?.markers?.length > 0 && (
              <div>
                <h3 className="font-bold text-gray-800 text-sm mb-3 flex items-center gap-2">
                  <span className="material-symbols-outlined text-emerald-500">
                    bar_chart
                  </span>
                  Lab Result Analysis
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {recommendations.markers.map((marker, i) => {
                    const st =
                      STATUS_STYLE[marker.status?.toLowerCase()] || defaultStatus;
                    return (
                      <div
                        key={i}
                        className="bg-white rounded-2xl border border-gray-100 hover:border-emerald-200 hover:shadow-md transition-all p-5"
                      >
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex items-center gap-2">
                            <span
                              className={`w-2.5 h-2.5 rounded-full shrink-0 ${st.dot}`}
                            />
                            <p className="text-sm font-bold text-gray-800">
                              {marker.name}
                            </p>
                          </div>
                          <span
                            className={`text-[11px] font-bold px-2 py-1 rounded-full flex items-center gap-1 ${st.badge}`}
                          >
                            <span
                              className={`material-symbols-outlined text-sm ${st.iconColor}`}
                            >
                              {st.icon}
                            </span>
                            {st.label}
                          </span>
                        </div>
                        {marker.value && (
                          <p className="text-xl font-black text-gray-800 mb-2">
                            {marker.value}
                          </p>
                        )}
                        <p className="text-xs text-gray-500 leading-relaxed">
                          {marker.advice}
                        </p>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Foods & Nutrients — two-column grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {/* Foods to Include */}
              {recommendations?.foods_to_include?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 p-5">
                  <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2 text-sm">
                    <span className="material-symbols-outlined text-emerald-500 text-lg">
                      check_circle
                    </span>
                    Foods to Include
                  </h3>
                  <ul className="space-y-2">
                    {recommendations.foods_to_include.map((food, i) => (
                      <li
                        key={i}
                        className="flex items-start gap-2 text-xs text-gray-600"
                      >
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                        {food}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Foods to Limit */}
              {recommendations?.foods_to_limit?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 p-5">
                  <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2 text-sm">
                    <span className="material-symbols-outlined text-red-400 text-lg">
                      cancel
                    </span>
                    Foods to Limit
                  </h3>
                  <ul className="space-y-2">
                    {recommendations.foods_to_limit.map((food, i) => (
                      <li
                        key={i}
                        className="flex items-start gap-2 text-xs text-gray-600"
                      >
                        <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
                        {food}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Key Nutrients */}
              {recommendations?.key_nutrients?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 p-5">
                  <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2 text-sm">
                    <span className="material-symbols-outlined text-amber-500 text-lg">
                      nutrition
                    </span>
                    Key Nutrients to Focus On
                  </h3>
                  <ul className="space-y-2">
                    {recommendations.key_nutrients.map((n, i) => (
                      <li
                        key={i}
                        className="flex items-start gap-2 text-xs text-gray-600"
                      >
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                        {n}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* General Advice */}
            {recommendations?.general_advice && (
              <div className="bg-white rounded-2xl border border-gray-100 p-6">
                <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2">
                  <span className="material-symbols-outlined text-emerald-500">
                    tips_and_updates
                  </span>
                  General Dietary Advice
                </h3>
                <p className="text-sm text-gray-600 leading-relaxed">
                  {recommendations.general_advice}
                </p>
              </div>
            )}

            {/* Raw Lab Results Table */}
            {labOrders.length > 0 && (
              <div className="bg-white rounded-2xl border border-gray-100 p-6">
                <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
                  <span className="material-symbols-outlined text-emerald-500">
                    biotech
                  </span>
                  Lab Results Used
                </h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="border-b border-gray-100">
                        <th className="text-left font-bold text-gray-500 pb-2 pr-4">
                          Test
                        </th>
                        <th className="text-left font-bold text-gray-500 pb-2 pr-4">
                          Result
                        </th>
                        <th className="text-left font-bold text-gray-500 pb-2">
                          Date
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {labOrders.map((l) => (
                        <tr
                          key={l._id}
                          className="hover:bg-gray-50 transition-colors"
                        >
                          <td className="py-2.5 pr-4 font-semibold text-gray-700">
                            {l.test_name}
                          </td>
                          <td className="py-2.5 pr-4 text-gray-600">
                            {l.result || (
                              <span className="text-gray-300 italic">
                                pending
                              </span>
                            )}
                          </td>
                          <td className="py-2.5 text-gray-400">
                            {new Date(l.ordered_at).toLocaleDateString("en-US", {
                              month: "short",
                              day: "numeric",
                              year: "numeric",
                            })}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Find Nutritionist CTA */}
            <div
              className="rounded-2xl p-6 text-white relative overflow-hidden"
              style={{
                background:
                  "linear-gradient(135deg,#16a34a 0%,#22c55e 55%,#4ade80 100%)",
              }}
            >
              <div className="absolute top-0 right-0 w-40 h-40 rounded-full -mr-12 -mt-12 bg-white/10" />
              <div className="relative flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <h3 className="font-black text-lg mb-1">
                    Want personalised nutrition advice?
                  </h3>
                  <p className="text-white/70 text-sm">
                    Connect with a certified nutritionist for a tailored diet
                    plan based on your health goals and medical history.
                  </p>
                </div>
                <button
                  onClick={() =>
                    navigate("/patient/doctors", {
                      state: { specialtyFilter: "Nutritionist" },
                    })
                  }
                  className="flex items-center gap-2 px-5 py-3 bg-white text-emerald-700 font-bold rounded-xl text-sm hover:scale-105 transition-all shadow-lg shrink-0"
                >
                  <span className="material-symbols-outlined text-sm">
                    person_search
                  </span>
                  Find Nutritionist
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </PatientLayout>
  );
}
